embed_assets: on

javascripts:
  workspace:
    - public/javascripts/jquery-latest.pack
    - public/javascripts/thickbox-compressed

stylesheets:
  common:
    - public/stylesheets/*.css
  workspace:
    - public/stylesheets/pages/workspace.css